title: "My Brain - Public Pages"
description: "Some subset of my notes"
theme: minima
# Or any other theme

# Optionally, default to `published: false` if you wanted to rely on Jekyll for skipping pages.
# Not strictly needed if you're physically removing the unpublished .md files anyway.
#defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       published: false
